java_library(
    name = "geocode",
    srcs = ["test_Geocode.java"],
    visibility = ["//src/User_Interface:__pkg__"],
)

java_library(
    name = "DBAccess",
    srcs = ["test_DB.java"],
    deps = ["//lib:mongodb","//lib:mongodb-sync", "//lib:bson","//lib:mongodb-streams"],
    visibility = ["//src/User_Interface:__pkg__"],
)

