java_import(
    name = "mongodb-sync",
    jars = [
        "mongodb-driver-sync-4.1.1.jar",
    ],
    visibility = ["//src/Connect:__pkg__"],
)

java_import(
    name = "bson",
    jars = [
        "bson-4.1.1.jar",
    ],
    visibility = ["//src/Connect:__pkg__"],
)

java_import(
    name = "mongodb-streams",
    jars = [
        "mongodb-driver-reactivestreams-4.1.1.jar",
    ],
    visibility = ["//src/Connect:__pkg__"],
)

java_import(
    name = "mongodb",
    jars = [
        "mongo-java-driver-3.12.8.jar",
    ],
    visibility = ["//src/Connect:__pkg__"],
)

java_import(
    name = "jackson",
    jars = [
        "jackson-databind-2.12.2.jar",
        "jackson-core-2.12.2.jar",
        "jackson-annotations-2.12.2.jar",
    ],
    visibility = ["//src/Connect:__pkg__"],
)